# Generated by Django 5.0.4 on 2024-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_classifier_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='town_or_village',
            new_name='booth',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='address_of_polling_station',
            new_name='town',
        ),
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
